### ISSUE TITLE
有办法把tbs浏览器播放视频横屏时“安装QQ浏览器”的提示去掉吗?

### ISSUE THREAD

**Issue by hytcyjb** [Ericsongyl/FalconBrowser#1]
我之前项目中也用tbs的，可是播放视频的时候有广告，不得不舍弃不使用；你那边有可以去掉的方法吗?或者是使用别的技术替代这个吗？

**Comment by Ericsongyl** [comment]
“安装QQ浏览器”的提示，我看了tbs X5的官方论坛，上面有回复说是设计是那样的[论坛回复](http://bbs.mb.qq.com/thread-1467305-1-1.html)；不过有一个办法就是：还是用X5的内核，不过视频全屏播放的功能有开发者自己实现，不用X5的全屏功能[点击查看](http://x5.tencent.com/tbs/technical.html#/detail/sdk/1/a1f54118-e2b7-43df-8189-8824e4ce5970)

**Comment by hytcyjb** [comment]
是的，去不了，视频也不能没有全屏播放功能；所以也就只能不用tbs了。

**Comment by Ericsongyl** [comment]
估计是腾讯为了推广他的QQ浏览器，所以在TBS的sdk中加了这种引导用户下载安装QQ浏览器的提示。因此，要想继续用TBS X5内核，视频的全屏功能就需要开发者自己实现。
`看如下示例代码：

Bundle data = new Bundle();

data.putBoolean("standardFullScreen", false);
//true表示标准全屏，false表示X5全屏；不设置默认false，

data.putBoolean("supportLiteWnd", false);
//false：关闭小窗；true：开启小窗；不设置默认true，

data.putInt("DefaultVideoScreen", 2);
//1：以页面内开始播放，2：以全屏开始播放；不设置默认：1

mWebView.getX5WebViewExtension().invokeMiscMethod("setVideoParams", data);
1) standardFullScreen 全屏设置

设置为true时，我们会回调WebChromeClient的onShowCustomView方法，由开发者自己实现全屏展示；

设置为false时，由我们实现全屏展示，我们实现全屏展示需要满足下面两个条件：

a. 我们 Webview初始化的Context必须是Activity类型的Context

b. 我们 Webview 所在的Activity要声明这个属性

android:configChanges="orientation|screenSize|keyboardHidden"
如果不满足这两个条件，standardFullScreen 自动置为 true

2) supportLiteWnd 小窗播放设置

前提standardFullScreen=false，这个条件才生效

设置为 true， 开启小窗功能

设置为 false，不使用小窗功能

3) DefaultVideoScreen 初始播放形态设置

a、以页面内形态开始播放

b、以全屏形态开始播放`

**Comment by hytcyjb** [comment]
但是如果继续使用tbs，播放视频时只能用小窗口，全屏时没办法传递事件过去，同时也无法保证播放时间的能够在小窗口、全屏之间顺利切换；但是我自己开发用webview的浏览器时遇到的坑太多了，处理起来也太麻烦了。
